sudo: true
language: cpp

compiler:
  - gcc

before_install:
  - if [ "$CXX" == "g++" ]; then sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test; fi
  - sudo pip install codecov # From https://github.com/travis-ci/travis-ci/issues/1705
  - sudo apt-get update -qq

#install:
  - if [ "$CXX" = "g++" ]; then sudo apt-get install -qq g++-4.8; fi
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8"; fi

script: 
 - cd ..
 - git clone https://github.com/richelbilderbeek/RibiClasses
 - git clone https://github.com/richelbilderbeek/RibiLibraries
 - ls
 - cd InvestigateMyClickWinners
 - qmake InvestigateMyClickWinnersConsole.pro
 - make
 - qmake InvestigateMyClickWinnersDesktop.pro
 - make

after_success:
  - codecov