sudo: true
language: cpp
compiler: gcc

addons: 
  apt: 
    packages: libboost-all-dev

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
  - sudo pip install codecov # From https://github.com/travis-ci/travis-ci/issues/1705

install: sudo apt-get install -qq g++-5

script: 
  - ./build.sh

after_success:
  - codecov
